"""Shared constants for benchmark result contracts."""

MAX_TRIALS = 8

ENGINE_NAME_OMLX = "omlx"
ENGINE_NAME_RAPID_MLX = "rapid-mlx"
ENGINE_NAME_MLX_LM = "mlx-lm"
ENGINE_NAME_OLLAMA = "ollama"
VALID_ENGINE_NAMES = {
    ENGINE_NAME_OMLX,
    ENGINE_NAME_RAPID_MLX,
    ENGINE_NAME_MLX_LM,
    ENGINE_NAME_OLLAMA,
}

TOKEN_COUNT_SOURCE_USAGE = "usage.completion_tokens"
TOKEN_COUNT_SOURCE_WORD_FALLBACK = "word_fallback"
TOKEN_COUNT_SOURCE_MIXED = "mixed"
TOKEN_COUNT_SOURCES = {
    TOKEN_COUNT_SOURCE_USAGE,
    TOKEN_COUNT_SOURCE_WORD_FALLBACK,
    TOKEN_COUNT_SOURCE_MIXED,
}

RAM_MEASUREMENT_PROCESS_RSS = "process_rss"
RAM_MEASUREMENT_SYSTEM_FALLBACK = "system_fallback"
RAM_MEASUREMENT_METHODS = {
    RAM_MEASUREMENT_PROCESS_RSS,
    RAM_MEASUREMENT_SYSTEM_FALLBACK,
}
