"""Shared constants for benchmark result contracts."""

MAX_TRIALS = 30
PUBLIC_BASELINE_TRIALS = 5
P95_MIN_TRIALS = 20
DEFAULT_THROUGHPUT_MAX_TOKENS = 100
SUSTAINED_THROUGHPUT_MAX_TOKENS = 1000
SUSTAINED_TRIALS = 1
SUSTAINED_PROGRESS_SAMPLE_INTERVAL_TOKENS = 100
BENCHMARK_REQUEST_TEMPERATURE = 0.0
BENCHMARK_REQUEST_TOP_P = 1.0

DEFAULT_RAM_SAMPLE_INTERVAL = 0.05
DEFAULT_THERMAL_SAMPLE_INTERVAL = 1.0
RECENT_BENCHMARK_WARNING_SECONDS = 300.0

# Phase durations and total runtime are rounded independently before validation.
PHASE_TIMING_TOLERANCE_SECONDS = 0.05
ERROR_RESPONSE_BODY_LIMIT = 500

ENGINE_NAME_OMLX = "omlx"
ENGINE_NAME_RAPID_MLX = "rapid-mlx"
ENGINE_NAME_VLLM_MLX = "vllm-mlx"
ENGINE_NAME_MLX_LM = "mlx-lm"
ENGINE_NAME_OLLAMA = "ollama"
# Keep in sync with engines.ENGINES and schema.EngineName. constants.py is kept
# dependency-light, so tests enforce the registry/schema match instead.
VALID_ENGINE_NAMES = {
    ENGINE_NAME_OMLX,
    ENGINE_NAME_RAPID_MLX,
    ENGINE_NAME_VLLM_MLX,
    ENGINE_NAME_MLX_LM,
    ENGINE_NAME_OLLAMA,
}

TOKEN_COUNT_SOURCE_USAGE = "usage.completion_tokens"
TOKEN_COUNT_SOURCE_WORD_FALLBACK = "word_fallback"
TOKEN_COUNT_SOURCE_MIXED = "mixed"

RAM_MEASUREMENT_PROCESS_RSS = "process_rss"
RAM_MEASUREMENT_SYSTEM_FALLBACK = "system_fallback"
